title: Terminal Guide for Designers
description: A friendly, practical guide to using the Mac Terminal for designers.
theme: minima
baseurl: ""
url: "https://milesfitzgerald.github.io/Terminalguidefordesigners"
markdown: kramdown
